// Copyright 2026 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style
// license that can be found in the LICENSE file.

package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"math/rand/v2"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"slices"
	"sort"
	"strings"
	"text/template"

	"golang.org/x/arch/arm64/instgen/xmlspec"
)

type tmplData struct {
	EncodingFuncs []funcData
	Insts         []instData
	InstsByName   []instsByName
	// All possible arg patterns are aggregated here.
	// They are unique with regard to [Class] and [Elms].
	// [Asm] is not considered for uniqueness.
	UniqueArgs []argData
	// All possible operand combinations are aggregated here.
	// They are unique with regard to the list of [Args].
	UniqueOpCombs []opCombData
	Constants     []constantData
}

type instsByName struct {
	Name  string
	Insts []instData // All these insts share the same GoOp code.
}

type constantData struct {
	ConstName string
	BinName   string
}

type funcData struct {
	Comments []string
	Body     string
	Name     string
}

type instData struct {
	GoOp      string
	FixedBits string
	Args      []argData
	Ops       opCombData
	Asm       string
}

type argData struct {
	// The global variable name of this arg pattern.
	Name  string
	Class string
	Asm   string
	Elms  []elmData
}

type opCombData struct {
	Name       string
	OpAsms     string
	ArgNames   []string
	BetterName string
}

type elmData struct {
	FuncName string
	EncName  string
}

type e2eData struct {
	GoOp   string
	Asm    string
	Binary string
	// highFeat is the feature order (see [operandTypeOrders]), it's used to
	// sort the e2e test data.
	highFeat int
}

const genTmpl = `// Code generated by 'instgen -o=$GOROOT # from go install golang.org/x/arch/arm64/instgen@latest'. DO NOT EDIT.

// The following constants are generated from the XML specification.

package arm64

// insts are grouped by [goOp].
var insts = [][]instEncoder{
{{- range .InstsByName}}
	// {{.Name}}
	{
{{- range .Insts}}
		// {{.Asm}} {{.Ops.OpAsms}}
		{
			goOp:      {{.GoOp}},
			fixedBits: {{.FixedBits}},
			args:      {{.Ops.BetterName}},
		},
{{- end}}
	},
{{- end}}
}

{{range .UniqueArgs}}
var {{.Name}} = operand{
	class: {{.Class}}, elemEncoders: []elemEncoder{
{{- range .Elms}}
		{{"{"}}{{.FuncName}}, {{.EncName}}{{"}"}},
{{- end}}
	},
}
{{end}}

{{range .UniqueOpCombs}}
var {{.BetterName}} = []operand{
{{- range .ArgNames}}
	{{.}},
{{- end}}
}
{{end}}
`

const encodingTmpl = `// Code generated by 'instgen -o=$GOROOT # from go install golang.org/x/arch/arm64/instgen@latest'.

package arm64

const (
  enc_NIL component = iota
{{- range .Constants}}
	{{.ConstName}}
{{- end}}
)
{{- range .EncodingFuncs}}
// {{.Name}} is the implementation of the following encoding logic:
{{- range .Comments}}
// {{.}}
{{- end}}
func {{.Name}}(v uint32) (uint32, bool) {
	{{.Body}}
}
{{- end}}
`

const goopsTmpl = `// Code generated by 'instgen -o=$GOROOT # from go install golang.org/x/arch/arm64/instgen@latest'. DO NOT EDIT.

package arm64

import "cmd/internal/obj"

const (
{{- range .}}
	{{.}}
{{- end}}
	ALAST
)
`

const anamesTmpl = `// Code generated by 'instgen -o=$GOROOT # from go install golang.org/x/arch/arm64/instgen@latest'. DO NOT EDIT.

package arm64

var sveAnames = []string{
	"SVESTART",
{{- range .}}
	"{{.}}",
{{- end}}
	"LAST",
}

func init() {
	Anames = append(Anames, sveAnames...)
}
`

const e2edataTmpl = `// Code generated by 'instgen -o=$GOROOT # from go install golang.org/x/arch/arm64/instgen@latest'. DO NOT EDIT.

#include "../../../../../runtime/textflag.h"

TEXT asmtest(SB),DUPOK|NOSPLIT,$-8
{{- range .}}
	{{.Asm}}{{.Binary}}
{{- end}}
	RET
`

var operandTypeOrders = map[string]int{
	"AC_ARNG":    0,
	"AC_PREG":    0,
	"AC_PREGZ":   0,
	"AC_PREGZM":  0,
	"AC_ZREG":    0,
	"AC_SPZGREG": 1,
	"AC_VREG":    1,
}

func readExistingGoOps(aoutPath string) map[string]bool {
	ops := make(map[string]bool)
	content, err := os.ReadFile(aoutPath)
	if err != nil {
		return ops
	}
	re := regexp.MustCompile(`\b(A[A-Z0-9_]+)\b`)
	matches := re.FindAllStringSubmatch(string(content), -1)
	for _, m := range matches {
		ops[m[1]] = true
	}
	return ops
}

// formatAndFlush executes the given template and writes it to the given file,
// the go file is formatted using gofmt.
// If outputDir is empty, it does nothing.
func formatAndFlush(outputDir string, filename string, data any, tmpl string) {
	if outputDir == "" {
		return
	}
	t, err := template.New("template").Parse(tmpl)
	if err != nil {
		log.Fatalf("Failed to parse template %s: %v", filename, err)
	}

	var buf bytes.Buffer
	if err := t.Execute(&buf, data); err != nil {
		log.Fatalf("Failed to execute template %s: %v", filename, err)
	}

	formatted := buf.Bytes()
	if strings.HasSuffix(filename, ".go") {
		formatted, err = format.Source(formatted)
		if err != nil {
			log.Printf("Failed to format generated source: %v", err)
			formatted = buf.Bytes()
		}
	}

	outputPath := filepath.Join(outputDir, filename)
	if err := os.WriteFile(outputPath, formatted, 0644); err != nil {
		log.Fatalf("Failed to write output file %s: %v", outputPath, err)
	}
	log.Printf("Generated %s", outputPath)
}

// Generate generates the Go code for the instruction table.
func Generate(insts []*xmlspec.InstructionParsed, outputDir string, genE2E bool) {
	// process encodingImpls, field them to make the comparison easier
	for k, v := range encodingImpls {
		uniformed := strings.Join(strings.Fields(k), " ")
		encodingImpls[uniformed] = v
	}

	// Collect constants
	encodingFuncs := make(map[string]int) // Map textExp to index
	encodingFuncComments := make(map[string][]string)

	// Pre-populate EncodingFuncs
	sortedEncodings := make([]string, 0, len(xmlspec.AllEncodingDescs))
	for k := range xmlspec.AllEncodingDescs {
		sortedEncodings = append(sortedEncodings, k)
	}
	sort.Strings(sortedEncodings)

	// Create map to store names early
	funcNames := make(map[int]string)
	encNames := make(map[int]string)

	for i, k := range sortedEncodings {
		encodingFuncs[k] = i + 1
		encodingFuncComments[k] = strings.Split(k, "\n")

		kUniformed := strings.Join(strings.Fields(k), " ")
		if b, ok := encodingImpls[kUniformed]; ok {
			funcNames[i+1] = b.name
			encNames[i+1] = b.encodedIn
		} else {
			funcNames[i+1] = fmt.Sprintf("encodeGen%d", i+1)
		}
	}

	// Collect A64Types and A64Feats, and Insts
	var instsData []instData
	newGoOps := make(map[string]bool)
	existingGoOps := readExistingGoOps(filepath.Join(outputDir, "a.out.go"))

	usedFuncIndices := make(map[int]bool)

	e2eTestData := make([]e2eData, 0)
	e2eErrorData := make([]e2eData, 0)
	for _, inst := range insts {
		if inst == nil {
			continue
		}
		isAlias := false
		for _, doc := range inst.DocVars {
			if doc.Key == "alias_mnemonic" {
				isAlias = true
				break
			}
		}
		if isAlias {
			// Alias instructions are not fully specified in their own XML files,
			// skip them.
			continue
		}

		for _, iclass := range inst.Classes.Iclass {
			if !iclass.RegDiagram.Parsed {
				continue
			}

			for _, encodingRaw := range iclass.Encodings {
				if !encodingRaw.Parsed {
					continue
				}

				if encodingRaw.Alias {
					// Alias encodings are not fully specified in their own section,
					// skip them.
					continue
				}

				encodings := xmlspec.SplitInstByRegWidth(encodingRaw)
				for _, encoding := range encodings {
					// Filtering logic:
					// 1. If 0 operands (len <= 1), keep with warning.
					// 2. If > 0 operands, ALL must be in operandTypeOrders.
					keep := true
					if len(encoding.Operands) <= 1 {
						log.Printf("Warning: instruction with 0 operands kept: %s", encoding.Asm)
					} else {
						for _, op := range encoding.Operands[1:] {
							if _, ok := operandTypeOrders[op.Typ]; !ok {
								keep = false
								break
							}
						}
					}

					if !keep {
						continue
					}

					if !existingGoOps[encoding.GoOp] {
						newGoOps[encoding.GoOp] = true
					} else {
						log.Printf("Warning: goOp %s already exists in a.out.go", encoding.GoOp)
					}

					validData, errData := constructInstance(&encoding)
					e2eTestData = append(e2eTestData, *validData)
					if errData != nil {
						e2eErrorData = append(e2eErrorData, *errData)
					}
					instData := instData{
						Asm:       encoding.GoOp[1:],
						GoOp:      encoding.GoOp,
						FixedBits: fmt.Sprintf("%#x", encoding.Binary),
					}

					for _, op := range encoding.Operands[1:] {
						arg := argData{
							Asm:   op.Name,
							Class: op.Typ,
						}
						if len(op.Elems) > 0 {
							for _, elm := range op.Elems {
								idx, ok := encodingFuncs[elm.TextExpWithRanges]
								if !ok {
									log.Printf("Warning: encoding func not found for %s", elm.TextExpWithRanges)
									continue
								}

								enc := encNames[idx]
								if enc == "" {
									// Fallback
									sym := xmlspec.EncodingDescsToEncodedIn[elm.TextExpWithRanges]
									// We actually do not have encodedInMap here yet, so just prefix "enc_"
									if sym == "" || sym == "nil" {
										enc = "enc_NIL"
									} else {
										v := sym
										v = strings.ReplaceAll(v, " :: ", "_")
										v = strings.ReplaceAll(v, "(", "")
										v = strings.ReplaceAll(v, ")", "")
										v = strings.ReplaceAll(v, "[", "")
										v = strings.ReplaceAll(v, "]", "")
										enc = fmt.Sprintf("enc_%s", v)
									}
								}
								arg.Elms = append(arg.Elms, elmData{
									FuncName: funcNames[idx],
									EncName:  enc,
								})
								usedFuncIndices[idx] = true
							}
						}
						instData.Args = append(instData.Args, arg)
					}
					instsData = append(instsData, instData)
				}
			}
		}
	}

	// Prepare template data
	data := tmplData{
		Insts: instsData,
	}

	// Collect constants
	encodedInMap := make(map[string]string) // raw string -> constant name
	var uniqueEncodedIn []string

	// Collect ALL constants from global map to ensure invariant names (enc_X)
	for _, v := range xmlspec.EncodingDescsToEncodedIn {
		if v == "" || v == "nil" {
			continue
		}
		if _, ok := encodedInMap[v]; !ok {
			encodedInMap[v] = ""
			uniqueEncodedIn = append(uniqueEncodedIn, v)
		}
	}
	sort.Strings(uniqueEncodedIn)

	// Identify used constants
	neededEncodedIn := make(map[string]bool)
	for k, idx := range encodingFuncs {
		if usedFuncIndices[idx] {
			if v := xmlspec.EncodingDescsToEncodedIn[k]; v != "" && v != "nil" {
				neededEncodedIn[v] = true
			}
		}
	}

	var constants []constantData
	for _, v := range uniqueEncodedIn {
		v0 := v
		v = strings.ReplaceAll(v, " :: ", "_")
		v = strings.ReplaceAll(v, "(", "")
		v = strings.ReplaceAll(v, ")", "")
		v = strings.ReplaceAll(v, "[", "")
		v = strings.ReplaceAll(v, "]", "")
		name := fmt.Sprintf("enc_%s", v)
		encodedInMap[v0] = name
		// Only add to output if used
		if neededEncodedIn[v0] {
			constants = append(constants, constantData{
				ConstName: name,
				BinName:   v0,
			})
		}
	}
	for i, k := range sortedEncodings {
		if !usedFuncIndices[i+1] {
			continue
		}
		sym := xmlspec.EncodingDescsToEncodedIn[k]
		if name, ok := encodedInMap[sym]; ok {
			sym = name
		} else {
			sym = "enc_NIL"
		}
		var body string
		kUniformed := strings.Join(strings.Fields(k), " ")
		var name string
		if b, ok := encodingImpls[kUniformed]; ok {
			body = b.body
			name = b.name
		} else {
			log.Printf("Warning: encoding func not found for\n%s\n", k)
			body = defaultEncodingTmpl
			name = fmt.Sprintf("encodeGen%d", i+1)
		}
		data.EncodingFuncs = append(data.EncodingFuncs, funcData{
			Comments: encodingFuncComments[k],
			Body:     body,
			Name:     name,
		})
	}
	data.Constants = constants

	// Now aggregate all arg patterns to unique globals.
	argMap := make(map[string]bool)
	var uniqueArgs []argData
	for i, inst := range instsData {
		for j, arg := range inst.Args {
			name := "a_" + arg.Class[3:] // remove AC_ prefix
			for _, elm := range arg.Elms {
				name += "_" + strings.TrimPrefix(elm.FuncName, "encode")
			}
			instsData[i].Args[j].Name = name
			arg.Name = name
			if !argMap[name] {
				argMap[name] = true
				uniqueArgs = append(uniqueArgs, arg)
			}
		}
	}
	data.UniqueArgs = uniqueArgs
	// Now aggregate all arg lists to unique globals.
	opCombMap := make(map[string]opCombData)
	var uniqueOpCombs []opCombData
	for i, inst := range instsData {
		name := "oc"
		argNames := []string{}
		argAsms := []string{}
		for _, arg := range inst.Args {
			name += "_" + arg.Name[2:] // remove a_ prefix
			for _, elm := range arg.Elms {
				name += "_" + strings.TrimPrefix(elm.FuncName, "encode")
			}
			argNames = append(argNames, arg.Name)
			argAsms = append(argAsms, arg.Asm)
		}
		if ops, ok := opCombMap[name]; ok {
			instsData[i].Ops = ops
		} else {
			ops := opCombData{
				Name:     name,
				ArgNames: argNames,
				OpAsms:   strings.Join(argAsms, ", "),
			}
			opCombMap[name] = ops
			uniqueOpCombs = append(uniqueOpCombs, ops)
			instsData[i].Ops = ops
		}
	}
	data.UniqueOpCombs = uniqueOpCombs

	// Figure out better names for the slices of asm operand
	// checkers/encoders.

	// Goal is to replace an "ugly name" with a sanitized
	// version of the instruction operand types; however, sometimes
	// there is more than one ugly name mapping to the same
	// nominal operands (an ugly name corresponds to an encoding).
	// Detect this, and for those cases where there's more than
	// one ugly name for the same operands, append a sequence
	// number.
	operandsToName := func(s string) string {
		s = strings.Replace(s, "<", "", -1)
		s = strings.Replace(s, ">", "", -1)
		s = strings.Replace(s, "/", "", -1)
		s = strings.Replace(s, ",", "_", -1)
		s = strings.Replace(s, ".", "_", -1)
		s = strings.Replace(s, " ", "_", -1)
		s = strings.Replace(s, "|", "", -1)
		return s
	}

	ot2ugly2Count := make(map[string]map[string]int)
	otSlice := []string{} // insertion order of operand types
	uglyInsertionOrder := make(map[string]int)

	for _, inst := range data.Insts {
		uglyName := inst.Ops.Name
		if x := uglyInsertionOrder[uglyName]; x == 0 {
			uglyInsertionOrder[uglyName] = 1 + len(uglyInsertionOrder)
		}
		operandTypes := inst.Ops.OpAsms
		if ot2ugly2Count[operandTypes] == nil {
			otSlice = append(otSlice, operandTypes)
			ot2ugly2Count[operandTypes] = make(map[string]int)
		}
		// keep track of how many instructions with this operand type
		// sequence use the exact same encoding.
		ot2ugly2Count[operandTypes][uglyName] += 1
	}

	// Map from ugly name to better name
	ugly2better := make(map[string]string)

	for _, x := range otSlice {
		// Get a canonical order of ugly names
		var uglies []string
		u2c := ot2ugly2Count[x]
		for c := range u2c {
			uglies = append(uglies, c)
		}

		if len(uglies) > 1 {
			// if there is more than one, sort into decreasing
			// frequency order, then sort by insertion order.
			sort.Slice(uglies, func(i, j int) bool {
				if c := u2c[uglies[j]] - u2c[uglies[i]]; c != 0 {
					return c < 0
				}
				return uglyInsertionOrder[uglies[i]] < uglyInsertionOrder[uglies[j]]
			})
			for j, u := range uglies {
				ugly2better[u] = fmt.Sprintf("%s__%d", operandsToName(x), j+1)
			}
		} else {
			// if only one, do not add a __N suffix.
			ugly2better[uglies[0]] = operandsToName(x)
		}
	}

	// Apply better name translations.
	for i, inst := range data.Insts {
		if arg := ugly2better[inst.Ops.Name]; arg != "" {
			data.Insts[i].Ops.BetterName = arg
		} else {
			data.Insts[i].Ops.BetterName = inst.Ops.Name
		}
	}

	for i, uoc := range data.UniqueOpCombs {
		if arg := ugly2better[uoc.Name]; arg != "" {
			data.UniqueOpCombs[i].BetterName = arg
		} else {
			data.UniqueOpCombs[i].BetterName = uoc.Name
		}
	}

	// Put these two slices into sensible orders.
	sort.Slice(data.UniqueOpCombs, func(i, j int) bool {
		return data.UniqueOpCombs[i].BetterName < data.UniqueOpCombs[j].BetterName
	})

	sort.Slice(data.UniqueArgs, func(i, j int) bool {
		return data.UniqueArgs[i].Name < data.UniqueArgs[j].Name
	})

	// Group instructions by name
	// Also sort them by their Go mnemonic.
	sort.Slice(data.Insts, func(i, j int) bool {
		return data.Insts[i].GoOp < data.Insts[j].GoOp
	})
	ibn := []instsByName{}
	prevGoOp := ""
	for _, inst := range data.Insts {
		if inst.GoOp != prevGoOp {
			ibn = append(ibn, instsByName{
				Name:  inst.GoOp[1:],
				Insts: []instData{},
			})
			prevGoOp = inst.GoOp
		}
		ibn[len(ibn)-1].Insts = append(ibn[len(ibn)-1].Insts, inst)
	}
	data.InstsByName = ibn

	// Generate inst_gen.go
	formatAndFlush(outputDir, "src/cmd/internal/obj/arm64/inst_gen.go", data, genTmpl)

	// Generate encoding_gen.go
	formatAndFlush(outputDir, "src/cmd/internal/obj/arm64/encoding_gen.go", data, encodingTmpl)

	// Generate goops_gen.go
	var sortedNewGoOps []string
	for k := range newGoOps {
		sortedNewGoOps = append(sortedNewGoOps, k)
	}
	sort.Strings(sortedNewGoOps)
	goopsPrefix := " obj.As = ASVESTART + 1 + iota"
	sortedNewGoOps[0] += goopsPrefix
	formatAndFlush(outputDir, "src/cmd/internal/obj/arm64/goops_gen.go", sortedNewGoOps, goopsTmpl)

	// Generate anames_gen.go
	for i := range sortedNewGoOps {
		sortedNewGoOps[i] = strings.TrimSuffix(sortedNewGoOps[i], goopsPrefix)
		sortedNewGoOps[i] = strings.TrimPrefix(sortedNewGoOps[i], "A")
	}
	formatAndFlush(outputDir, "src/cmd/internal/obj/arm64/anames_gen.go", sortedNewGoOps, anamesTmpl)

	if genE2E {
		slices.SortStableFunc(e2eTestData, func(i, j e2eData) int {
			if i.highFeat != j.highFeat {
				return i.highFeat - j.highFeat
			}
			return strings.Compare(i.GoOp, j.GoOp)
		})
		slices.SortStableFunc(e2eErrorData, func(i, j e2eData) int {
			if i.highFeat != j.highFeat {
				return i.highFeat - j.highFeat
			}
			return strings.Compare(i.GoOp, j.GoOp)
		})
		// Generate arm64sveenc.s
		formatAndFlush(outputDir, "src/cmd/asm/internal/asm/testdata/arm64sveenc.s", e2eTestData, e2edataTmpl)
		// Generate arm64sveerror.s
		formatAndFlush(outputDir, "src/cmd/asm/internal/asm/testdata/arm64sveerror.s", e2eErrorData, e2edataTmpl)
	}
}

// Mappings for operand patterns to concrete registers
var regMap = map[string]string{
	"Zd":  "Z",
	"Zda": "Z",
	"Zdn": "Z",
	"Zn":  "Z",
	"Zm":  "Z",
	"Za":  "Z",
	"Zk":  "Z",

	"Pd":  "P",
	"Pdn": "P",
	"Pdm": "P",
	"Pn":  "P",
	"Pm":  "P",
	"Pg":  "P",
	"PNd": "PN",
	"Pv":  "P",

	"Vd": "V",
	"Vn": "V",
	"Vm": "V",
}

// Arrangement variables, also includes predication cases.
var arrMap = map[string]bool{
	"Tb": true, // arrangement variables
	"T":  true, // arrangement variables
	"ZM": true, // predication variables
}

// Z, P reg arrangements, used for variable mutation.
var sveArr = []string{"B", "H", "S", "D", "Q"}
var svePred = []string{"M", "Z"}

// V reg arrangements, used for variable mutation.
var neonArrGNU = []string{"16B", "1D", "4H", "8H", "2S", "4S", "2D", "1Q"}
var neonArrGo = []string{"B16", "D1", "H4", "H8", "S2", "S4", "D2", "Q1"}

// assembleGNU assembles the given assembly string using GNU toolchain and returns the hex.
func assembleGNU(s string) (string, error) {
	// Create temp file
	tmpName := "temp_probe.s"
	if err := os.WriteFile(tmpName, []byte(s+"\n"), 0644); err != nil {
		return "", err
	}
	defer os.Remove(tmpName)

	// Run as
	cmd := exec.Command("aarch64-linux-gnu-as", "-march=all", tmpName, "-o", "temp_probe.o")
	if out, err := cmd.CombinedOutput(); err != nil {
		return "", fmt.Errorf("as failed: %s", out)
	}
	defer exec.Command("rm", "temp_probe.o").Run()

	// Run objdump
	cmd = exec.Command("aarch64-linux-gnu-objdump", "-d", "temp_probe.o")
	out, err := cmd.CombinedOutput()
	if err != nil {
		return "", err
	}

	// Parse output
	lines := strings.Split(string(out), "\n")
	for _, l := range lines {
		l = strings.TrimSpace(l)
		// The first text line contains the hex.
		if strings.Contains(l, "0:") {
			parts := strings.Fields(l)
			// parts[0] is offset:, parts[1] is hex
			if len(parts) >= 2 {
				if len(parts[1]) == 8 {
					return parts[1], nil
				}
			}
		}
	}
	return "", fmt.Errorf("no hex found")
}

// reverseHex reverses the byte order of a hex string.
// this is required for Go's e2e test.
func reverseHex(h string) string {
	if len(h) != 8 {
		return h
	}
	return h[6:8] + h[4:6] + h[2:4] + h[0:2]
}

// constructInstance takes an [Encoding] and tries to generate a
// valid Go assembly instance of it and returns the e2eData for this instance.
// The construction is deterministic.
//
// This function requires the availablity of the GNU toolchain.
// Special instructions are elided, they are documented in the comments.
// Technically we can skip them early before we do the construction, but
// we kept them after the construction for future verification.
func constructInstance(enc *xmlspec.EncodingParsed) (*e2eData, *e2eData) {
	var name string
	// Try to construct two assembly, one in Go the other in GNU.
	// The trial succeeds once the GNU one is accepted by the GNU toolchain.
	rng := rand.New(rand.NewPCG(uint64(42), uint64(1024)))
	// Try 100 times until we find one that's accepted by the GNU toolchain.
	// constructInstance does not understand the encoding level constraint, so
	// it just try until a valid one is found.
	var highFeat int
	var gnuErr error
	var errCase *e2eData
	var validCase *e2eData
	for range 100 {
		goAsmOps := make([]string, 0)
		gnuAsmOps := make([]string, 0)
		// Useful for pruning AC_ARNG, AC_PREG, AC_PREGZM, AC_ZREG.
		// ABS  <Zd>.<T>, <Pg>/Z, <Zn>.<T>
		// the 2 instances of <T> should be exactly the same...
		// Key is the random number selected.
		regCache := map[string]int{}
		arrCache := map[string]int{}
		cachedOrNew := func(cache map[string]int, key string, n int) int {
			if v, ok := cache[key]; ok {
				if errCase != nil || len(enc.Operands) == 0 {
					// Give the error case a chance to be triggered.
					return v
				}
			}
			v := rng.IntN(n)
			cache[key] = v
			return v
		}
		for i, op := range enc.Operands {
			if i == 0 {
				// First operand is the instruction name.
				name = op.Name
				continue
			}
			opName := op.Name
			if _, ok := operandTypeOrders[op.Typ]; !ok {
				log.Fatalf("Unsupported operand type in constructInstance: %s, enc: %s", op.Typ, enc.String())
			}
			highFeat = max(highFeat, operandTypeOrders[op.Typ])
			if op.Typ == "AC_ARNG" || op.Typ == "AC_PREG" || op.Typ == "AC_PREGZM" || op.Typ == "AC_ZREG" {
				// Operands that takes SVE registers and arrangement.

				var parts []string
				var isPred bool
				if strings.Contains(opName, ".") {
					parts = strings.Split(opName, ".")
				} else {
					parts = strings.Split(opName, "/")
					isPred = true
				}
				if len(parts) == 0 {
					log.Fatalf("Unrecognized operand: %s", opName)
				}
				regName := strings.TrimSuffix(strings.TrimPrefix(parts[0], "<"), ">")
				var arrName string
				if len(parts) > 1 {
					arrName = strings.TrimSuffix(strings.TrimPrefix(parts[1], "<"), ">")
				}
				reg := regMap[regName]
				if arrMap[arrName] || errCase == nil {
					// Give error case a random mutation to trigger an error.
					// Variables, needs mutation
					switch reg {
					case "Z":
						regIdx := cachedOrNew(regCache, regName, 32)
						arrIdx := cachedOrNew(arrCache, arrName, len(sveArr))
						asmOp := fmt.Sprintf("Z%d.%s", regIdx, sveArr[arrIdx])
						gnuAsmOps = append([]string{asmOp}, gnuAsmOps...)
						// go operand order is gnu reversed
						goAsmOps = append(goAsmOps, asmOp)
					case "P", "PN":
						regIdx := cachedOrNew(regCache, regName, 15)
						if isPred {
							arrIdx := cachedOrNew(arrCache, arrName, len(svePred))
							// Go use "." for predication, GNU use "/"
							gnuAsmOps = append([]string{fmt.Sprintf("%s%d/%s", reg, regIdx, svePred[arrIdx])}, gnuAsmOps...)
							goAsmOps = append(goAsmOps, fmt.Sprintf("%s%d.%s", reg, regIdx, svePred[arrIdx]))
						} else {
							arrIdx := cachedOrNew(arrCache, arrName, len(sveArr))
							asmOp := fmt.Sprintf("%s%d.%s", reg, regIdx, sveArr[arrIdx])
							gnuAsmOps = append([]string{asmOp}, gnuAsmOps...)
							goAsmOps = append(goAsmOps, asmOp)
						}
					case "V":
						regIdx := cachedOrNew(regCache, regName, 32)
						arrIdx := cachedOrNew(arrCache, arrName, len(neonArrGNU))
						gnuAsmOps = append([]string{fmt.Sprintf("V%d.%s", regIdx, neonArrGNU[arrIdx])}, gnuAsmOps...)
						goAsmOps = append(goAsmOps, fmt.Sprintf("V%d.%s", regIdx, neonArrGo[arrIdx]))
					}
				} else {
					// Fixed arrangement or predications
					if arrName != "" {
						arrName = "." + arrName
					}
					switch reg {
					case "Z":
						regIdx := cachedOrNew(regCache, regName, 32)
						asmOp := fmt.Sprintf("Z%d%s", regIdx, arrName)
						gnuAsmOps = append([]string{asmOp}, gnuAsmOps...)
						goAsmOps = append(goAsmOps, asmOp)
					case "P", "PN":
						regIdx := cachedOrNew(regCache, regName, 15)
						if isPred {
							var arrNameGNU string
							if arrName != "" {
								arrNameGNU = "/" + arrName[1:]
							}
							gnuAsmOps = append([]string{fmt.Sprintf("%s%d%s", reg, regIdx, arrNameGNU)}, gnuAsmOps...)
							goAsmOps = append(goAsmOps, fmt.Sprintf("%s%d%s", reg, regIdx, arrName))
						} else {
							asmOp := fmt.Sprintf("%s%d%s", reg, regIdx, arrName)
							gnuAsmOps = append([]string{asmOp}, gnuAsmOps...)
							goAsmOps = append(goAsmOps, asmOp)
						}
					case "V":
						log.Fatalf("Unexpected V with fixed arrangement: %s", opName)
					}
				}
			} else if op.Typ == "AC_SPZGREG" || op.Typ == "AC_VREG" {
				// Operands that takes scalar or NEON vector registers.
				// There arn't that much of shapes, just enumerate them...
				var goPrefix string
				switch op.Typ {
				case "AC_SPZGREG":
					goPrefix = "R"
				case "AC_VREG":
					goPrefix = "V"
				}
				var gnuPrefix string
				switch op.Typ {
				case "AC_SPZGREG":
					if strings.Contains(op.Name, "W") {
						gnuPrefix = "W"
					} else if strings.Contains(op.Name, "<R>") {
						// We know the parser will append the width to the GoOp as a suffix.
						switch enc.GoOp[len(enc.GoOp)-1] {
						case 'W':
							gnuPrefix = "W"
						default:
							// X does not have a suffix, as we know from the parser rules.
							gnuPrefix = "X"
						}
					} else {
						gnuPrefix = "X"
					}
				case "AC_VREG":
					if strings.Contains(op.Name, "<V>") || strings.Contains(op.Name, "<Dd>") {
						// We know the parser will append the width to the GoOp as a suffix.
						// Also <Dd> literally means the width is D.
						suffix := enc.GoOp[len(enc.GoOp)-1]
						switch suffix {
						case 'B', 'H', 'S', 'D':
							gnuPrefix = string(suffix)
						default:
							log.Fatalf("Unrecognized SIMD vector width: %c, enc: %s", suffix, enc.String())
						}
					} else {
						gnuPrefix = "V"
					}
				}
				var goAsmOp, gnuAsmOp string
				switch op.Name {
				case "<R><n|SP>", "<Xd|SP>", "<Xn|SP>", "<R><d>", "<R><dn>", "<R><m>",
					"<R><n>", "<Wdn>", "<Xd>", "<Xdn>", "<Xm>", "<Xn>", "<Dd>", "<V><d>",
					"<V><dn>", "<V><m>", "<V><n>":
					// R32 is RSP
					regIdx := cachedOrNew(regCache, op.Name, 64)
					goAsmOp = fmt.Sprintf("%s%d", goPrefix, regIdx)
					gnuAsmOp = fmt.Sprintf("%s%d", gnuPrefix, regIdx)
					if regIdx >= 31 && regIdx < 48 {
						goAsmOp = "RSP"
						if gnuPrefix == "W" {
							gnuAsmOp = "WSP"
						} else {
							gnuAsmOp = "SP"
						}
					}
					if regIdx >= 56 {
						goAsmOp = "ZR"
						if gnuPrefix == "W" {
							gnuAsmOp = "WZR"
						} else if gnuPrefix == "X" {
							gnuAsmOp = "XZR"
						}
					}
				default:
					log.Fatalf("Unrecognized operand: %s", op.Name)
				}
				gnuAsmOps = append([]string{gnuAsmOp}, gnuAsmOps...)
				goAsmOps = append(goAsmOps, goAsmOp)
			}
		}
		// Try to assemble the GNU version.
		gnuAsm := fmt.Sprintf(".arch_extension sve2p1\n%s %s", name, strings.Join(gnuAsmOps, ", "))
		hex, err := assembleGNU(gnuAsm)
		goAsmStr := fmt.Sprintf("%s %s", enc.GoOp[1:], strings.Join(goAsmOps, ", "))
		if err != nil {
			gnuErr = err
			if errCase == nil {
				errCase = &e2eData{
					GoOp:     enc.GoOp[1:],
					Asm:      fmt.Sprintf("%-50s", goAsmStr),
					Binary:   "// ERROR \"illegal combination from SVE\"",
					highFeat: highFeat,
				}
			}
			continue
		}
		if validCase == nil {
			validCase = &e2eData{
				GoOp:     enc.GoOp[1:],
				Asm:      fmt.Sprintf("%-50s", goAsmStr),
				Binary:   "// " + reverseHex(hex),
				highFeat: highFeat,
			}
		}
		if name == "CMPLT" || name == "CMPLE" || name == "CMPLO" || name == "CMPLS" {
			// These instructions has an aliased instruction that's not accepted by the GNU assembler.
			// However at this moment Go does not support the aliased instruction.
			// These e2e test cases will be compared to another non-aliased instruction of the same
			// mnemonic, causing a test failure.
			// Before we support alias in Go, we skip these test cases.
			todoCase := e2eData{GoOp: enc.GoOp[1:], Asm: fmt.Sprintf("// TODO: %s", name), highFeat: highFeat}
			return &todoCase, errCase
		}
		if validCase == nil || (errCase == nil && len(gnuAsmOps) != 0) {
			// We must collect at least one valid and one error case.
			// if the instruction has 0 operands, we can't generate an error case.
			continue
		}

		return validCase, errCase
	}
	if name == "ADDQP" || name == "ADDSUBP" || name == "SCVTFLT" || name == "UCVTFLT" {
		// Very new instructions
		// GNU toolchain 2.45 doesn't know about these instruction yet.
		todoCase := e2eData{GoOp: enc.GoOp[1:], Asm: fmt.Sprintf("// TODO: %s", name), highFeat: highFeat}
		return &todoCase, &todoCase
	}
	if enc.Asm == "BFMMLA  <Zda>.H, <Zn>.H, <Zm>.H" ||
		enc.Asm == "FMMLA  <Zda>.H, <Zn>.H, <Zm>.H" ||
		enc.Asm == "SABAL  <Zda>.<T>, <Zn>.<Tb>, <Zm>.<Tb>" ||
		enc.Asm == "SCVTF  <Zd>.<T>, <Zn>.<Tb>" ||
		enc.Asm == "SDOT  <Zda>.H, <Zn>.B, <Zm>.B" ||
		enc.Asm == "SUBP  <Zdn>.<T>, <Pg>/M, <Zdn>.<T>, <Zm>.<T>" ||
		enc.Asm == "UABAL  <Zda>.<T>, <Zn>.<Tb>, <Zm>.<Tb>" ||
		enc.Asm == "UCVTF  <Zd>.<T>, <Zn>.<Tb>" ||
		enc.Asm == "UDOT  <Zda>.H, <Zn>.B, <Zm>.B" {
		// Very new instruction encodings
		// GNU toolchain 2.45 doesn't know about these specific encodings yet.
		todoCase := e2eData{GoOp: enc.GoOp[1:], Asm: fmt.Sprintf("// TODO: %s", enc.Asm), highFeat: highFeat}
		return &todoCase, &todoCase
	}
	log.Fatalf("Failed to construct instance for %s: %v", enc.Asm, gnuErr)
	return &e2eData{GoOp: enc.GoOp[1:]}, &e2eData{GoOp: enc.GoOp[1:]}
}
